### ISSUE TITLE
Episode Field filled with extra text

### ISSUE THREAD

**Issue by pr0j3ctx** [sunsettrack4/zattoo_tvh#3] opened 2018-04-10 09:52 UTC
Hello.

I have in all fields with Season and Episode in it this extra text.

S1 E7,"xlime_recommendations_possible":false

![grafik](https://user-images.githubusercontent.com/3234533/38549945-8259f796-3cb5-11e8-8ad3-40805e0032c0.png)

Is it an Problem by grabbing xmltv?

Greets pr0

**Comment by sunsettrack4** [comment] 2018-04-10 10:03
I haven't seen that before. Do you use v0.3.7 or the latest version from master branch?

**Comment by pr0j3ctx** [comment] 2018-04-10 11:01
The Version v0.3.7

**Comment by sunsettrack4** [comment] 2018-04-10 18:12
I'm not able to reproduce that problem, as I can't find the string "xlime_recommendations_possible" in my EPG ID files. What kind of Zattoo account do you have, and did you register/login via any social media account?

You can help me to fix this issue by attaching the workfile here (~/ztvh/epg/20180412/workfile).

![img_20180410_203755](https://user-images.githubusercontent.com/12012294/38576733-4107fd84-3cff-11e8-808f-b987092f5785.jpg)

**Comment by pr0j3ctx** [comment] 2018-04-12 04:53
I`m using Zattoo CH Premium with an Mail-Account. Non Social.
Here are my workfile
https://gist.github.com/pr0j3ctx/7b026ffd2055536da917e6b73ee78370

**Comment by sunsettrack4** [comment] 2018-04-12 19:16
As I can see in your workfile, there are two new cases to be considered. Due to the fact that I only use the free version, I didn't observe that xlime string. Next update will follow tomorrow.

**Comment by pr0j3ctx** [comment] 2018-04-13 12:37
I´ve fixed it quick and dirty with this command after creating epg file
`sed -i s/\,\"xlime_recommendations_possible\"\:false//g ~/ztvh/zattoo_fullepg.xml`

**Comment by sunsettrack4** [comment] 2018-04-13 21:30
@pr0j3ctx Please check the commit https://github.com/sunsettrack4/zattoo_tvh/commit/f0f3c30f399b1786c80a2b97a1c8029ca81a4ccb
Fixed in v0.3.8

**Comment by pr0j3ctx** [comment] 2018-04-16 05:58
Sorry, but after upgrading to the new commit I get this error after running the script.

> Validating EPG XMLTV file...
> - ERROR: XMLTV FILE VALIDATION FAILED! -
> --- DONE ---

**Comment by sunsettrack4** [comment] 2018-04-16 06:20
Please retry the full version 0.3.8 and report back. If the error still occurs, please attach a new workfile and the XMLTV file here.

**Comment by pr0j3ctx** [comment] 2018-04-16 09:19
Same issue after complete reset of ztvh folder from master inlcuding new setup/config.
working file = https://gist.github.com/pr0j3ctx/232e401faef643e3fadbf71a63541e9b
Do you mean this file? 20180416_zattoo_fullepg_ERROR.xml

**Comment by sunsettrack4** [comment] 2018-04-16 09:32
Yes, I mean that file. Issue reopened, I'll take a look later today.

**Comment by pr0j3ctx** [comment] 2018-04-16 09:46
Couldn`t upload it to github issue. Here the link to another space
http://ztools.betelgeuse.uberspace.de/20180416_zattoo_fullepg_ERROR.xml

**Comment by sunsettrack4** [comment] 2018-04-16 10:38
Can you fix this tag mismatch problem on your own by removing this line?
https://github.com/sunsettrack4/zattoo_tvh/blob/master/zguide_xmltv.sh#L42

**Comment by pr0j3ctx** [comment] 2018-04-16 11:00
Removing this line doesn`t fix the issue. Same fault.
https://gist.githubusercontent.com/pr0j3ctx/33b68372659c097eee9196b5248e05e7/raw/fd79029a465896034b2d7ff1b4d8e041aa035528/20180416_zattoo_fullepg_ERROR.xml

https://gist.githubusercontent.com/pr0j3ctx/33b68372659c097eee9196b5248e05e7/raw/fd79029a465896034b2d7ff1b4d8e041aa035528/workfile

**Comment by sunsettrack4** [comment] 2018-04-16 18:16
@pr0j3ctx Thanks again for your help and for your files, I found the issue and fixed it in commit https://github.com/sunsettrack4/zattoo_tvh/commit/8e0398fbeb4839475e4db1ff381f180a64fa85c0. New version 0.3.9 released - feel free to retry :+1:

**Closed as completed** 2018-04-16 18:19 UTC
Labels: bug

**Comment by pr0j3ctx** [comment] 2018-04-18 05:14
Fine. It works!
